development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: wpbdc_development
  username: generessler
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: wpbdc_test
  username: generessler
  password:
  allow_concurrency: true
  pool: 5
  min_messages: error

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: wpbdc_production
  username: generessler
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning
