development:
  adapter: postgresql
  encoding: unicode
  database: wpbdc_development
  pool: 5
  username: eugeneressler
  password:
  allow_concurrency: true

test:
  adapter: postgresql
  encoding: unicode
  database: wpbdc_test
  pool: 5
  username: eugeneressler
  password:
  allow_concurrency: true
